name: build-angular
run-name: ${{ github.actor }} is deploying a new version of ESL Web
on:
  push:
    branches:
      - 'release'
  pull_request:
    branches:
      - 'release'
jobs:
  build:
   runs-on: ubuntu-latest
   container: node:22.3
   environment: web runner
   steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Install Deps
      run: npm ci
    - name: angular build
      run: npx ng build
    - name: deploy via scp to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.FTPHOST }}
        username: ${{ secrets.FTPUSER }}
        password: ${{ secrets.FTPPW }}
        port: ${{ secrets.FTPPORT }}
        source: "dist/esl-web/browser/es-US/."
        target: "public_html/"
        overwrite: true
        strip_components: 4
        tar_tmp_path: "."
